name: Lint

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: prettier
        run: yarn prettier --check packages/*/src/**/*.{ts,tsx}
